class Orchestrator:
    def __init__(self, ollama_url: str | None = ...) -> None: ...
    def code(self, task: str, language: str | None = ...) -> str: ...
    def list_models(self) -> list[str]: ...
