//! Model training pipeline — fine-tune Ollama models via LoRA/DPO.
//!
//! Uses `ollama create` with Modelfiles and adapter files to produce
//! specialized models versioned as `{base}-{specialty}-v{N}`.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use thiserror::Error;
use tracing::info;

#[derive(Debug, Error)]
pub enum TrainingError {
    #[error("ollama error: {0}")]
    Ollama(String),
    #[error("dataset error: {0}")]
    Dataset(String),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("config error: {0}")]
    Config(String),
}

pub type TrainResult<T> = std::result::Result<T, TrainingError>;

/// Training method.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TrainingMethod {
    /// LoRA adapter fine-tuning.
    Lora,
    /// Direct Preference Optimization.
    Dpo,
}

/// Training configuration.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TrainingConfig {
    pub base_model: String,
    pub new_model_name: String,
    pub method: TrainingMethod,
    pub dataset_path: PathBuf,
    pub epochs: u32,
    pub learning_rate: f32,
    pub batch_size: u32,
    pub output_dir: PathBuf,
}

impl Default for TrainingConfig {
    fn default() -> Self {
        Self {
            base_model: "qwen3.5:4b".into(),
            new_model_name: "qwen3.5:4b-custom-v1".into(),
            method: TrainingMethod::Lora,
            dataset_path: PathBuf::from("data/training.jsonl"),
            epochs: 3,
            learning_rate: 0.0001,
            batch_size: 4,
            output_dir: PathBuf::from("models"),
        }
    }
}

/// Benchmark result comparing base vs fine-tuned model.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct BenchmarkResult {
    pub base_model: String,
    pub fine_tuned_model: String,
    pub prompts_tested: u32,
    pub base_avg_latency_ms: f64,
    pub fine_tuned_avg_latency_ms: f64,
    pub base_quality_score: f32,
    pub fine_tuned_quality_score: f32,
    pub improvement_pct: f32,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

/// Training pipeline executor.
pub struct TrainingPipeline {
    ollama_url: String,
}

impl TrainingPipeline {
    pub fn new(ollama_url: impl Into<String>) -> Self {
        Self {
            ollama_url: ollama_url.into(),
        }
    }

    /// Prepare a Modelfile for `ollama create`.
    pub fn create_modelfile(&self, config: &TrainingConfig) -> TrainResult<String> {
        let adapter_path = config.output_dir.join(format!(
            "{}_adapter.bin",
            config.new_model_name.replace(':', "-")
        ));

        let modelfile = format!(
            "# Modelfile generated by airllm-training\n\
             FROM {base}\n\
             \n\
             # Adapter (LoRA/DPO weights)\n\
             ADAPTER {adapter}\n\
             \n\
             # Parameters\n\
             PARAMETER temperature {temp}\n\
             PARAMETER top_p 0.9\n\
             \n\
             # System prompt (optional, set by agent config)\n\
             # SYSTEM \"You are a specialized assistant.\"\n",
            base = config.base_model,
            adapter = adapter_path.display(),
            temp = 0.7,
        );

        Ok(modelfile)
    }

    /// Validate a training dataset (JSONL format).
    pub fn validate_dataset(path: &Path) -> TrainResult<DatasetStats> {
        let raw = std::fs::read_to_string(path)
            .map_err(|e| TrainingError::Dataset(format!("read error: {e}")))?;
        let mut entries = 0u32;
        let mut valid = 0u32;
        for line in raw.lines() {
            if line.trim().is_empty() {
                continue;
            }
            entries += 1;
            if let Ok(json) = serde_json::from_str::<serde_json::Value>(line) {
                if json.is_object() {
                    valid += 1;
                }
            }
        }
        if entries == 0 {
            return Err(TrainingError::Dataset("dataset is empty".into()));
        }
        if valid < entries / 2 {
            return Err(TrainingError::Dataset(format!(
                "only {valid}/{entries} entries are valid JSON objects"
            )));
        }
        Ok(DatasetStats {
            total_entries: entries,
            valid_entries: valid,
        })
    }

    /// Execute the training pipeline (simulated — real version calls Ollama API).
    pub async fn train(&self, config: &TrainingConfig) -> TrainResult<TrainingResult> {
        info!(
            base = %config.base_model,
            new = %config.new_model_name,
            method = ?config.method,
            "starting training pipeline"
        );

        // 1. Validate dataset
        let stats = Self::validate_dataset(&config.dataset_path)?;
        info!(entries = stats.valid_entries, "dataset validated");

        // 2. Create Modelfile
        let modelfile = self.create_modelfile(config)?;
        let modelfile_path = config.output_dir.join("Modelfile");
        std::fs::create_dir_all(&config.output_dir)?;
        std::fs::write(&modelfile_path, &modelfile)?;

        // 3. Simulate training (real version would call `ollama create`)
        // In production: `ollama create {new_model_name} -f {modelfile_path}`
        info!("training simulated — in production, this calls `ollama create`");

        // 4. Create a dummy adapter file
        let adapter_path = config.output_dir.join(format!(
            "{}_adapter.bin",
            config.new_model_name.replace(':', "-")
        ));
        std::fs::write(&adapter_path, b"# LoRA adapter placeholder")?;

        Ok(TrainingResult {
            model_name: config.new_model_name.clone(),
            modelfile_path,
            adapter_path,
            dataset_stats: stats,
            method: config.method.clone(),
            epochs: config.epochs,
            created_at: chrono::Utc::now(),
        })
    }

    /// Benchmark base vs fine-tuned model.
    pub async fn benchmark(
        &self,
        base_model: &str,
        fine_tuned_model: &str,
        prompts: &[String],
    ) -> TrainResult<BenchmarkResult> {
        use std::time::Instant;

        let client = reqwest::Client::builder()
            .timeout(std::time::Duration::from_secs(120))
            .build()
            .map_err(|e| TrainingError::Ollama(e.to_string()))?;

        let mut base_latencies = Vec::new();
        let mut fine_latencies = Vec::new();
        let mut base_quality = 0.0f32;
        let mut fine_quality = 0.0f32;

        for prompt in prompts {
            // Test base model
            let start = Instant::now();
            let resp = self.call_ollama(&client, base_model, prompt).await;
            if let Ok(text) = resp {
                base_latencies.push(start.elapsed().as_millis() as f64);
                base_quality += Self::score_response(&text, prompt);
            }

            // Test fine-tuned model
            let start = Instant::now();
            let resp = self.call_ollama(&client, fine_tuned_model, prompt).await;
            if let Ok(text) = resp {
                fine_latencies.push(start.elapsed().as_millis() as f64);
                fine_quality += Self::score_response(&text, prompt);
            }
        }

        let n = prompts.len() as f64;
        let base_avg = base_latencies.iter().sum::<f64>() / base_latencies.len().max(1) as f64;
        let fine_avg = fine_latencies.iter().sum::<f64>() / fine_latencies.len().max(1) as f64;
        let base_q = base_quality / n as f32;
        let fine_q = fine_quality / n as f32;
        let improvement = if base_q > 0.0 {
            (fine_q - base_q) / base_q * 100.0
        } else {
            0.0
        };

        Ok(BenchmarkResult {
            base_model: base_model.into(),
            fine_tuned_model: fine_tuned_model.into(),
            prompts_tested: prompts.len() as u32,
            base_avg_latency_ms: base_avg,
            fine_tuned_avg_latency_ms: fine_avg,
            base_quality_score: base_q,
            fine_tuned_quality_score: fine_q,
            improvement_pct: improvement,
            created_at: chrono::Utc::now(),
        })
    }

    async fn call_ollama(
        &self,
        client: &reqwest::Client,
        model: &str,
        prompt: &str,
    ) -> TrainResult<String> {
        let url = format!("{}/api/chat", self.ollama_url);
        let resp = client
            .post(&url)
            .json(&serde_json::json!({
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "stream": false,
            }))
            .send()
            .await
            .map_err(|e| TrainingError::Ollama(e.to_string()))?;

        let json: serde_json::Value = resp.json().await.map_err(|e| TrainingError::Ollama(e.to_string()))?;
        let text = json
            .get("message")
            .and_then(|m| m.get("content"))
            .and_then(|c| c.as_str())
            .unwrap_or("");
        Ok(text.to_string())
    }

    /// Simple quality heuristic: response length and non-empty.
    fn score_response(response: &str, prompt: &str) -> f32 {
        if response.is_empty() {
            return 0.0;
        }
        let len_score = (response.len() as f32 / 500.0).min(1.0);
        let relevance = if response.contains(prompt.split_whitespace().next().unwrap_or("")) {
            0.5
        } else {
            0.0
        };
        len_score * 0.5 + relevance + 0.5
    }

    /// List fine-tuned models (by naming convention).
    pub async fn list_fine_tuned(&self) -> TrainResult<Vec<String>> {
        let url = format!("{}/api/tags", self.ollama_url);
        let resp = reqwest::get(&url)
            .await
            .map_err(|e| TrainingError::Ollama(e.to_string()))?;
        let json: serde_json::Value = resp.json().await.map_err(|e| TrainingError::Ollama(e.to_string()))?;
        let models = json
            .get("models")
            .and_then(|m| m.as_array())
            .map(|arr| {
                arr.iter()
                    .filter_map(|m| m.get("name").and_then(|n| n.as_str()).map(String::from))
                    .filter(|name| name.contains("-v") || name.contains("-social") || name.contains("-code"))
                    .collect()
            })
            .unwrap_or_default();
        Ok(models)
    }
}

/// Dataset statistics.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct DatasetStats {
    pub total_entries: u32,
    pub valid_entries: u32,
}

/// Training result.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TrainingResult {
    pub model_name: String,
    pub modelfile_path: PathBuf,
    pub adapter_path: PathBuf,
    pub dataset_stats: DatasetStats,
    pub method: TrainingMethod,
    pub epochs: u32,
    pub created_at: chrono::DateTime<chrono::Utc>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_create_modelfile() {
        let pipeline = TrainingPipeline::new("http://localhost:11434");
        let config = TrainingConfig::default();
        let modelfile = pipeline.create_modelfile(&config).unwrap();
        assert!(modelfile.contains("FROM qwen3.5:4b"));
        assert!(modelfile.contains("ADAPTER"));
    }

    #[test]
    fn test_validate_dataset() {
        let dir = std::env::temp_dir();
        let path = dir.join("test_dataset.jsonl");
        std::fs::write(&path, r#"{"prompt":"hello","response":"hi"}"#).unwrap();
        let stats = TrainingPipeline::validate_dataset(&path).unwrap();
        assert_eq!(stats.total_entries, 1);
        assert_eq!(stats.valid_entries, 1);
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn test_validate_empty_dataset() {
        let dir = std::env::temp_dir();
        let path = dir.join("empty.jsonl");
        std::fs::write(&path, "").unwrap();
        let result = TrainingPipeline::validate_dataset(&path);
        assert!(result.is_err());
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn test_score_response() {
        assert_eq!(TrainingPipeline::score_response("", "test"), 0.0);
        assert!(TrainingPipeline::score_response("hello world this is a response", "hello") > 0.0);
    }
}